"""created by in address

Revision ID: 0e23ea70a4de
Revises: cc67ca5c741f
Create Date: 2023-12-22 18:10:12.091127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0e23ea70a4de'
down_revision: Union[str, None] = 'cc67ca5c741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'created_by')
    # ### end Alembic commands ###
