"""added_partner_table

Revision ID: 1255b426e0f0
Revises: 1b89baf13e2f
Create Date: 2024-01-04 14:26:07.416064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1255b426e0f0'
down_revision: Union[str, None] = '1b89baf13e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'partner', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'partner_id')
    op.drop_table('partner')
    # ### end Alembic commands ###
