"""added_partner_in_return

Revision ID: 14e3a4154bd3
Revises: f275acd177ae
Create Date: 2024-01-08 12:50:22.812881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '14e3a4154bd3'
down_revision: Union[str, None] = 'f275acd177ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'returns', 'partner', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'partner_id')
    # ### end Alembic commands ###
