"""order id in returns

Revision ID: 37c956dd444e
Revises: a2902370f1cb
Create Date: 2024-01-24 14:55:07.910963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '37c956dd444e'
down_revision: Union[str, None] = 'a2902370f1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'returns', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'order_id')
    # ### end Alembic commands ###
