"""pickup address id in order

Revision ID: 47c42ec18b39
Revises: 0e23ea70a4de
Create Date: 2023-12-23 02:05:19.548939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '47c42ec18b39'
down_revision: Union[str, None] = '0e23ea70a4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pickup_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'address', ['pickup_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'pickup_address_id')
    # ### end Alembic commands ###
