"""added_channel_table

Revision ID: 5c5b4f6f90ea
Revises: 1255b426e0f0
Create Date: 2024-01-04 14:53:40.532635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5c5b4f6f90ea'
down_revision: Union[str, None] = '1255b426e0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'channel', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'channel_id')
    op.drop_table('channel')
    # ### end Alembic commands ###
