"""added_waybill_no_in_returns

Revision ID: b22e84a9c5dd
Revises: 14e3a4154bd3
Create Date: 2024-01-09 11:46:33.592152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b22e84a9c5dd'
down_revision: Union[str, None] = '14e3a4154bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('returns', sa.Column('waybill_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('returns', 'waybill_no')
    # ### end Alembic commands ###
