"""added_invoice_no_in_channel

Revision ID: b5d9ced77563
Revises: 5c5b4f6f90ea
Create Date: 2024-01-04 15:15:51.511403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b5d9ced77563'
down_revision: Union[str, None] = '5c5b4f6f90ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('invoice_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('order', 'channel')
    op.drop_column('order', 'channel_invoice_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('channel_invoice_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('channel', 'invoice_no')
    # ### end Alembic commands ###
