"""add col modification

Revision ID: cc67ca5c741f
Revises: 54c8e47708b9
Create Date: 2023-12-22 18:00:04.705374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cc67ca5c741f'
down_revision: Union[str, None] = '54c8e47708b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('address', sa.Column('line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('address', 'address_line1')
    op.drop_column('address', 'address_line2')
    op.add_column('order', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'comment')
    op.add_column('address', sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('address', 'line2')
    op.drop_column('address', 'line1')
    # ### end Alembic commands ###
