"""img url cols add in product

Revision ID: cf93d96ba6bc
Revises: d88682ae43de
Create Date: 2024-01-31 14:38:18.373849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cf93d96ba6bc'
down_revision: Union[str, None] = 'd88682ae43de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weighing_scale_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('with_label_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'with_label_img')
    op.drop_column('product', 'weighing_scale_img')
    # ### end Alembic commands ###
