"""drop address id in order return

Revision ID: d88682ae43de
Revises: 37c956dd444e
Create Date: 2024-01-26 21:07:34.592171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd88682ae43de'
down_revision: Union[str, None] = '37c956dd444e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('drop_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'address', ['drop_address_id'], ['id'])
    op.add_column('returns', sa.Column('drop_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'returns', 'address', ['drop_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'drop_address_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'drop_address_id')
    # ### end Alembic commands ###
